spring:
  application:
    name: nacos-consumer-feign
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# feign 启动 熔断器
feign:
  sentinel:
    enabled: true


server:
  port: 9092

management:
  endpoints:
    web:
      exposure:
        include: "*"
